remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark"
  back_home_text: "home"
  appearance_toggle: true 
  date_format: "%Y-%m-%d"
  show_description: false 
  show_navbar: true # show h orizontal navbar
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml
  # options for "home" page

 home:
    title_projects: Statistics
